// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-12-06
//     Description: EndPoints class for the table "DocumentoIdentidad"
// </auto-generated>
// -----------------------------------------------------------------------------

using Microsoft.AspNetCore.Http.HttpResults;

using Mozo.ApiSeguridad.Helper;
using Mozo.MaestroBusiness;
using Mozo.Model.Maestro;

namespace Mozo.Api.Maestro;
/// <summary>
/// Clase estatica que para llamar al grupo de end points "DocumentoIdentidad".
/// </summary>
public static partial class DocumentoIdentidadEndPoints
{
    /// <summary>
    /// Función que devuelve el grupo de end points de la entidad "DocumentoIdentidad".
    /// </summary>
    public static RouteGroupBuilder MapDocumentoIdentidad(this RouteGroupBuilder g)
    {
        g.WithSecurity();

        g.MapGet("/active", SelAllActiveAsync)
          .WithResponses<IEnumerable<DocumentoIdentidadModel>>(StatusCodes.Status200OK)
          .WithDescription("Obtener todos los Documentos de Identidad");
        return g;
    }

}
public static partial class DocumentoIdentidadEndPoints
{

    static async Task<IResult>
       SelAllActiveAsync(IDocumentoIdentidadBusiness IDocumentoIdentidad)
    {      
        IEnumerable<DocumentoIdentidadModel> r = await IDocumentoIdentidad.SelAllActiveAsync();
        return Results.Ok(r);
    }

}

