// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-12-06
//     Description: EndPoints class for the table "Pais"
// </auto-generated>
// -----------------------------------------------------------------------------

using Microsoft.AspNetCore.Http.HttpResults;

using Mozo.ApiSeguridad.Helper;
using Mozo.MaestroBusiness;
using Mozo.Model.Maestro;
using Mozo.Model.Seguridad;

namespace Mozo.Api.Maestro;
/// <summary>
/// Clase estatica que para llamar al grupo de end points "Pais".
/// </summary>
public static partial class PaisEndPoints
{
    /// <summary>
    /// Función que devuelve el grupo de end points de la entidad "Pais".
    /// </summary>
    public static RouteGroupBuilder MapPais(this RouteGroupBuilder g)
    {
        g.WithSecurity();  

        g.MapGet("/active", SelAllActiveAsync)
          .WithResponses<IEnumerable<PaisModel>>(StatusCodes.Status200OK)
          .WithDescription("Obtener todos los Paises");

        return g;
    }

}
public static partial class PaisEndPoints
{
    static async Task<IResult>
        SelAllActiveAsync(IPaisBusiness IPais)
    {      
        IEnumerable<PaisModel> r = await IPais.SelAllActiveAsync();
        return Results.Ok(r);
    }

}

