// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-12-06
//     Description: EndPoints class for the table "trftipogeneral"
// </auto-generated>
// -----------------------------------------------------------------------------

using Microsoft.AspNetCore.Http.HttpResults;

using Mozo.ApiSeguridad.Helper;
using Mozo.MaestroBusiness;
using Mozo.Model.Maestro;

namespace Mozo.Api.Maestro;
/// <summary>
/// Clase estatica que para llamar al grupo de end points "trftipogeneral".
/// </summary>
public static partial class TipoGeneralEndPoints
{
/// <summary>
/// Función que devuelve el grupo de end points de la entidad "trftipogeneral".
/// </summary>
    public static RouteGroupBuilder MapTipoGeneral(this RouteGroupBuilder g)
    {
        g.DisableAntiforgery().RequireAuthorization();
        g.MapGet("/{cogrupo:int}/{cotipo:int}", SelByIdAsync);
        g.MapGet("/active", SelAllActiveAsync);
        g.MapGet("/modulos/active", SelAllActiveByModuloAsync);
        return g;
    }

}
public static partial class TipoGeneralEndPoints
{

    static async Task<Results<Ok<TipoGeneralModel>, NotFound, ValidationProblem>> SelByIdAsync(int cogrupo, int cotipo, ITipoGeneralBusiness ITipoGeneral, UserClaims user)
    {
        TipoGeneralModel m = new() { CoGrupo = cogrupo, CoTipo = cotipo };
        
        TipoGeneralModel? i = await ITipoGeneral.SelByIdAsync(m);
        if (i == null)
            return TypedResults.NotFound();
        return TypedResults.Ok(i);
    }
    static async Task<Results<Ok<IEnumerable<TipoGeneralModel>>, ValidationProblem>> SelAllActiveAsync(TipoGeneralFilter f, ITipoGeneralBusiness ITipoGeneral, UserClaims user)
    {
      
        IEnumerable<TipoGeneralModel> r = await ITipoGeneral.SelAllActiveAsync(new());
        return TypedResults.Ok(r);
    }

    static async Task<Results<Ok<IEnumerable<TipoGeneralModel>>, ValidationProblem>> SelAllActiveByModuloAsync(TipoGeneralFilter f, ITipoGeneralBusiness ITipoGeneral, UserClaims user)
    {
      
        IEnumerable<TipoGeneralModel> r = await ITipoGeneral.SelAllActiveByModuloAsync(new());
        return TypedResults.Ok(r);
    }

}

