// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: EndPoints class for the table "trftipoparticular"
// </auto-generated>
// -----------------------------------------------------------------------------
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OutputCaching;

using Mozo.ApiSeguridad.Helper;
using Mozo.CatalogoBusiness;
using Mozo.MaestroBusiness;
using Mozo.Model;
using Mozo.Model.Catalogo;
using Mozo.Model.Maestro;

namespace Mozo.Api.Maestro;
/// <summary>
/// Clase estatica que para llamar al grupo de end points "trftipoparticular".
/// </summary>
public static partial class TipoParticularEndPoints
{
    /// <summary>
    /// Función que devuelve el grupo de end points de la entidad "trftipoparticular".
    /// </summary>
    public static RouteGroupBuilder MapTipoParticular(this RouteGroupBuilder g)
    {
        g.DisableAntiforgery().RequireAuthorization();
        g.MapPost("/", InsertAsync);
        g.MapPut("/", UpdateAsync);
        g.MapDelete("/{cogrupo:int}/{cotipo:int}", DeleteByIdAsync);

        g.MapGet("/{cogrupo:int}/{cotipo:int}", SelByIdAsync);
        g.MapGet("/", SelAllAsync).AllowAnonymous();

        g.MapPatch("/state", UpdateStateAsync);
        g.MapPatch("/command", UpdateCommandAsync);
        g.MapPatch("/default", UpdateDefaultAsync);

        g.MapGet("/active", SelAllActiveAsync);

        g.MapGet("/hijos", SelAllHijoAsync);
        g.MapGet("/hijos/active", SelAllActiveHijoAsync);
        g.MapGet("/hijos/grupos/active", SelAllActiveHijoByGrupoAsync);
        g.MapGet("/modulos/grupos", SelAllGrupoByModuloAsync);

        g.MapGet("/next-orden", SelOrdenNextAsync);
        g.MapGet("/grupos/{cotipo:int}", SelByIdGrupoAsync);

        return g;
    }

}
public static partial class TipoParticularEndPoints
{
    static async Task<Results<Created<int?>, ValidationProblem>> InsertAsync([FromBody] TipoParticularModel m, IOutputCacheStore outputCacheStore, ITipoParticularBusiness ITipo, UserClaims user)
    {        
        m.CoTipo = await ITipo.InsertAsync(m);
        await outputCacheStore.EvictByTagAsync("Tipo_SelAllActive", default);
        return TypedResults.Created($"/{m.CoTipo}", m.CoTipo);
    }

    static async Task<Results<Ok<int?>, ValidationProblem>> UpdateAsync([FromBody] TipoParticularModel m, IOutputCacheStore outputCacheStore, ITipoParticularBusiness ITipo, UserClaims user)
    {
        
        await ITipo.UpdateAsync(m);
        await outputCacheStore.EvictByTagAsync("Tipo_SelAllActive", default);
        return TypedResults.Ok(m.CoTipo);
    }
    static async Task<Results<Ok<int?>, ValidationProblem>> UpdateCommandAsync([FromBody] TipoParticularModel m, IOutputCacheStore outputCacheStore, ITipoParticularBusiness ITipo, UserClaims user)
    {
        
        await ITipo.UpdateCommandAsync(m);
        await outputCacheStore.EvictByTagAsync("Tipo_SelAllActive", default);
        return TypedResults.Ok(m.CoTipo);
    }
    static async Task<Results<NoContent, ValidationProblem>> DeleteByIdAsync(int cogrupo, int cotipo, IOutputCacheStore outputCacheStore, ITipoParticularBusiness ITipo, UserClaims user)
    {
        TipoParticularModel m = new() { CoGrupo = cogrupo, CoTipo = cotipo };
        
        await ITipo.DeleteByIdAsync(m);
        await outputCacheStore.EvictByTagAsync("Tipo_SelAllActive", default);
        return TypedResults.NoContent();
    }
    static async Task<Results<Ok<int?>, ValidationProblem>> UpdateStateAsync([FromBody] TipoParticularModel m, IOutputCacheStore outputCacheStore, ITipoParticularBusiness ITipo, UserClaims user)
    {
        
        await ITipo.UpdateStateAsync(m);
        await outputCacheStore.EvictByTagAsync("Tipo_SelAllActive", default);
        return TypedResults.Ok(m.CoTipo);
    }
    static async Task<Results<Ok<int?>, ValidationProblem>> UpdateDefaultAsync([FromBody] TipoParticularModel m, IOutputCacheStore outputCacheStore, ITipoParticularBusiness ITipo, UserClaims user)
    {
        
        await ITipo.UpdateDefaultAsync(m);
        await outputCacheStore.EvictByTagAsync("Tipo_SelAllActive", default);
        return TypedResults.Ok(m.CoTipo);
    }
    static async Task<Results<Ok<IEnumerable<TipoParticularModel>>, ValidationProblem>> SelAllGrupoByModuloAsync([AsParameters] TipoParticularDto f, ITipoParticularBusiness ITipo, UserClaims user)
    {       
        return TypedResults.Ok(await ITipo.SelAllGrupoByModuloAsync(new()));
    }

    //static async Task<Results<Ok<IEnumerable<TipoParticularModel>>, ValidationProblem>> SelAllAsync(TipoParticularDto f, ITipoBusiness ITipo, UserClaims user)
    //{       
    //    return TypedResults.Ok(await ITipo.SelAllAsync(new()));
    //}

    static async Task<Results<Ok<PaginationModel<TipoParticularModel>>, ValidationProblem, NotFound>> SelAllAsync([AsParameters] TipoParticularDto f, ITipoParticularBusiness ITipo, UserClaims user)
    {
        int rowCount = await ITipo.SelAllCountAsync(f);
        IEnumerable<TipoParticularModel> r = await ITipo.SelAllAsync(f);
        PaginationModel<TipoParticularModel> p = new(r, rowCount, f.PageSize, f.PageIndex);
        return TypedResults.Ok(p);
    }

    private static IEnumerable<TipoParticularModel> GetAll2(IEnumerable<TipoParticularModel> r)
    {
        List<TipoParticularModel> r2 = r.ToList();
        List<TipoParticularModel> listTmp = r2.FindAll(x => x.FlDefault == 1);
        if (listTmp.Count() > 0)
            r2.FindAll(x => x.FlDefault == 1).ForEach(y => y.FlDefault = 0);
        return r2;
    }

    static async Task<Results<Ok<IEnumerable<TipoParticularModel>>, ValidationProblem>> SelAllActiveAsync([AsParameters] TipoParticularDto f, ITipoParticularBusiness ITipo, UserClaims user)
    {       
        return TypedResults.Ok(await ITipo.SelAllActiveAsync(new()));
    }

    static async Task<Results<Ok<IEnumerable<TipoParticularModel>>, ValidationProblem>> SelAllHijoAsync([AsParameters] TipoParticularDto f, ITipoParticularBusiness ITipo, UserClaims user)
    {       
        IEnumerable<TipoParticularModel> r = await ITipo.SelAllHijoAsync(new());
        r = GetAll2(r);
        return TypedResults.Ok(r);
    }

    static async Task<Results<Ok<IEnumerable<TipoParticularModel>>, ValidationProblem>> SelAllActiveHijoAsync([AsParameters] TipoParticularDto f, ITipoParticularBusiness ITipo, UserClaims user)
    {      
        IEnumerable<TipoParticularModel> r = await ITipo.SelAllActiveHijoAsync(new());
        return TypedResults.Ok(r);
    }

    static async Task<Results<Ok<IEnumerable<TipoParticularModel>>, ValidationProblem>> SelAllActiveHijoByGrupoAsync([AsParameters] TipoParticularDto f, ITipoParticularBusiness ITipo, UserClaims user)
    {       
        IEnumerable<TipoParticularModel> r = await ITipo.SelAllActiveHijoByGrupoAsync(new());
        return TypedResults.Ok(r);
    }


    static async Task<Results<Ok<TipoParticularModel>, NotFound, ValidationProblem>> SelByIdAsync(int cogrupo, int cotipo, ITipoParticularBusiness ITipo, UserClaims user)
    {
        TipoParticularModel m = new() { CoGrupo = cogrupo, CoTipo = cotipo };
        

        TipoParticularModel? i = await ITipo.SelByIdAsync(m);
        if (i == null)
            return TypedResults.NotFound();
        return TypedResults.Ok(i);
    }



    static async Task<Results<Ok<int>, NotFound, ValidationProblem>> SelOrdenNextAsync([AsParameters] TipoParticularDto f, ITipoParticularBusiness ITipo, UserClaims user)
    {       
        return TypedResults.Ok(await ITipo.SelOrdenNextAsync(new()));
    }


    static async Task<Results<Ok<TipoParticularModel>, NotFound, ValidationProblem>> SelByIdGrupoAsync([AsParameters] TipoParticularDto f, ITipoParticularBusiness ITipo, UserClaims user)
    {
        TipoParticularModel? i = await ITipo.SelByIdGrupoAsync(new());
        if (i == null)
            return TypedResults.NotFound();
        return TypedResults.Ok(i);
    }

}

