// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-02
//     Description: EndPoints class for the table "tblatributo"
// </auto-generated>
// -----------------------------------------------------------------------------

using Microsoft.AspNetCore.Http.HttpResults;

using Mozo.ApiSeguridad.Helper;
using Mozo.CatalogoBusiness;
using Mozo.Model.Catalogo;

using System.Collections.Generic;
using System.Threading.Tasks;

namespace Mozo.Api.Catalogo;
/// <summary>
/// Clase estatica que para llamar al grupo de end points "tblatributo".
/// </summary>
public static partial class AtributoEndPoints
{
    /// <summary>
    /// Función que devuelve el grupo de end points de la entidad "tblatributo".
    /// </summary>
    public static RouteGroupBuilder MapAtributo(this RouteGroupBuilder g)
    {
        g.DisableAntiforgery().RequireAuthorization();
        g.MapPost("/", InsertAsync);
        g.MapPut("/", UpdateAsync);
        g.MapPatch("/state", UpdateStateAsync);
        g.MapDelete("/{coatributo:int}", DeleteByIdAsync);
        g.MapGet("/", SelAllAsync);
        g.MapGet("/active", SelAllActiveAsync);
        g.MapGet("/{coatributo:int}", SelByIdAsync);
        return g;
    }
}
/// <summary>
/// Clase estatica donde se encuentran los procedimientos y funciones de los end points "tblatributo".
/// </summary>
public static partial class AtributoEndPoints
{

    static async Task<Results<Created<int?>, ValidationProblem>> InsertAsync(AtributoModel m, IAtributoBusiness IAtributo, UserClaims user)
    {       
        m.CoAtributo = await IAtributo.InsertAsync(m);
        return TypedResults.Created($"/{m.CoAtributo}", m.CoAtributo);
    }

    static async Task<Results<Ok<int?>, ValidationProblem>> UpdateAsync(AtributoModel m, IAtributoBusiness IAtributo, UserClaims user)
    {        
        await IAtributo.UpdateAsync(m);
        return TypedResults.Ok(m.CoAtributo);
    }

    static async Task<Results<Ok<int?>, ValidationProblem>> UpdateStateAsync(AtributoModel m, IAtributoBusiness IAtributo, UserClaims user)
    {
        
        await IAtributo.UpdateStateAsync(m);
        return TypedResults.Ok(m.CoAtributo);
    }

    static async Task<Results<NoContent, ValidationProblem>> DeleteByIdAsync(int coatributo, IAtributoBusiness IAtributo, UserClaims user)
    {
        AtributoModel m = new() { CoAtributo = coatributo };
        
        await IAtributo.DeleteByIdAsync(m);
        return TypedResults.NoContent();
    }

    static async Task<Results<Ok<IEnumerable<AtributoModel>>, ValidationProblem, NotFound>> SelAllAsync([AsParameters] AtributoFilter f, IAtributoBusiness IAtributo, UserClaims user)
    {        
        IEnumerable<AtributoModel> r = await IAtributo.SelAllAsync(new());
        return TypedResults.Ok(r);
    }

    static async Task<Results<Ok<IEnumerable<AtributoModel>>, ValidationProblem, NotFound>> SelAllActiveAsync([AsParameters] AtributoFilter f, IAtributoBusiness IAtributo, UserClaims user)
    {       
        IEnumerable<AtributoModel> r = await IAtributo.SelAllActiveAsync(new());
        return TypedResults.Ok(r);
    }

    static async Task<Results<Ok<AtributoModel>, NotFound, ValidationProblem>> SelByIdAsync(int coatributo, IAtributoBusiness IAtributo, UserClaims user)
    {
        AtributoModel m = new() { CoAtributo = coatributo };
        
        AtributoModel? i = await IAtributo.SelByIdAsync(m);
        if (i == null)
            return TypedResults.NotFound();
        return TypedResults.Ok(i);
    }

}
