// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: EndPoints class for the table "tblproductoprecio"
// </auto-generated>
// -----------------------------------------------------------------------------

using Microsoft.AspNetCore.Http.HttpResults;

using Mozo.ApiSeguridad.Helper;
using Mozo.CatalogoBusiness;
using Mozo.Model.Catalogo;

using System.Collections.Generic;
using System.Threading.Tasks;

namespace Mozo.Api.Catalogo;
/// <summary>
/// Clase estatica que para llamar al grupo de end points "tblproductoprecio".
/// </summary>
public static partial class ProductoPrecioEndPoints
{
/// <summary>
/// Función que devuelve el grupo de end points de la entidad "tblproductoprecio".
/// </summary>
	public static RouteGroupBuilder MapProductoPrecio(this RouteGroupBuilder g)
	{
		g.DisableAntiforgery().RequireAuthorization();
		g.MapPost("/", InsertAsync);
		g.MapPut("/", UpdateAsync);
		g.MapPatch("/state", UpdateStateAsync);
		g.MapDelete("/{coproductoprecio:int}", DeleteByIdAsync);
		g.MapGet("/", SelAllAsync);
		g.MapGet("/active", SelAllActiveAsync);
		g.MapGet("/{coproductoprecio:int}", SelByIdAsync);
		return g;
	}
}
/// <summary>
/// Clase estatica donde se encuentran los procedimientos y funciones de los end points "tblproductoprecio".
/// </summary>
public static partial class ProductoPrecioEndPoints
{

	static async Task<Results<Created<int?>, ValidationProblem>> InsertAsync(ProductoPrecioModel m, IProductoPrecioBusiness IProductoprecio, UserClaims user)
	{
		
		m.CoProductoPrecio = await IProductoprecio.InsertAsync(m);
		return TypedResults.Created($"/{m.CoProductoPrecio}", m.CoProductoPrecio);
	}

	static async Task<Results<Ok<int?>, ValidationProblem>> UpdateAsync(ProductoPrecioModel m, IProductoPrecioBusiness IProductoprecio, UserClaims user)
	{
		
		await IProductoprecio.UpdateAsync(m);
		return TypedResults.Ok(m.CoProductoPrecio);
	}

	static async Task<Results<Ok<int?>, ValidationProblem>> UpdateStateAsync(ProductoPrecioModel m, IProductoPrecioBusiness IProductoprecio, UserClaims user)
	{
		
		await IProductoprecio.UpdateStateAsync(m);
		return TypedResults.Ok(m.CoProductoPrecio);
	}

	static async Task<Results<NoContent, ValidationProblem>> DeleteByIdAsync(int coproductoprecio, IProductoPrecioBusiness IProductoprecio, UserClaims user)
	{
		ProductoPrecioModel m = new() { CoProductoPrecio = coproductoprecio};
		
		await IProductoprecio.DeleteByIdAsync(m);
		return TypedResults.NoContent();
	}

	static async Task<Results<Ok<IEnumerable<ProductoPrecioModel>>, ValidationProblem, NotFound>> SelAllAsync([AsParameters] ProductoPrecioFilter f, IProductoPrecioBusiness IProductoprecio, UserClaims user)
	{
	
		IEnumerable<ProductoPrecioModel> r = await IProductoprecio.SelAllAsync(new());
		return TypedResults.Ok(r);
	}

	static async Task<Results<Ok<IEnumerable<ProductoPrecioModel>>, ValidationProblem, NotFound>> SelAllActiveAsync([AsParameters] ProductoPrecioFilter f, IProductoPrecioBusiness IProductoprecio, UserClaims user)
	{
		
		IEnumerable<ProductoPrecioModel> r = await IProductoprecio.SelAllActiveAsync(new());
		return TypedResults.Ok(r);
	}

	static async Task<Results<Ok<ProductoPrecioModel>, NotFound, ValidationProblem>> SelByIdAsync(int coproductoprecio, IProductoPrecioBusiness IProductoprecio, UserClaims user)
	{
		ProductoPrecioModel m = new() {CoProductoPrecio = coproductoprecio};
		
		ProductoPrecioModel? i = await IProductoprecio.SelByIdAsync(m);
		if (i == null)
			return TypedResults.NotFound();
		return TypedResults.Ok(i);
	}

}
