// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: EndPoints class for the table "tblproductostock"
// </auto-generated>
// -----------------------------------------------------------------------------

using Microsoft.AspNetCore.Http.HttpResults;

using Mozo.ApiSeguridad.Helper;
using Mozo.CatalogoBusiness;
using Mozo.Model.Catalogo;

using System.Collections.Generic;
using System.Threading.Tasks;

namespace Mozo.Api.Catalogo;
/// <summary>
/// Clase estatica que para llamar al grupo de end points "tblproductostock".
/// </summary>
public static partial class ProductoStockEndPoints
{
/// <summary>
/// Función que devuelve el grupo de end points de la entidad "tblproductostock".
/// </summary>
	public static RouteGroupBuilder MapProductoStock(this RouteGroupBuilder g)
	{
		g.DisableAntiforgery().RequireAuthorization();
		g.MapPost("/", InsertAsync);
		g.MapPut("/", UpdateAsync);
		g.MapPatch("/state", UpdateStateAsync);
		g.MapDelete("/{coproductostock:int}", DeleteByIdAsync);
		g.MapGet("/", SelAllAsync);
		g.MapGet("/active", SelAllActiveAsync);
		g.MapGet("/{coproductostock:int}", SelByIdAsync);
		return g;
	}
}
/// <summary>
/// Clase estatica donde se encuentran los procedimientos y funciones de los end points "tblproductostock".
/// </summary>
public static partial class ProductoStockEndPoints
{

	static async Task<Results<Created<int?>, ValidationProblem>> InsertAsync(ProductoStockModel m, IProductoStockBusiness IProductostock, UserClaims user)
	{
		
		m.CoProductoStock = await IProductostock.InsertAsync(m);
		return TypedResults.Created($"/{m.CoProductoStock}", m.CoProductoStock);
	}

	static async Task<Results<Ok<int?>, ValidationProblem>> UpdateAsync(ProductoStockModel m, IProductoStockBusiness IProductostock, UserClaims user)
	{
		
		await IProductostock.UpdateAsync(m);
		return TypedResults.Ok(m.CoProductoStock);
	}

	static async Task<Results<Ok<int?>, ValidationProblem>> UpdateStateAsync(ProductoStockModel m, IProductoStockBusiness IProductostock, UserClaims user)
	{
		
		await IProductostock.UpdateStateAsync(m);
		return TypedResults.Ok(m.CoProductoStock);
	}

	static async Task<Results<NoContent, ValidationProblem>> DeleteByIdAsync(int coproductostock, IProductoStockBusiness IProductostock, UserClaims user)
	{
		ProductoStockModel m = new() { CoProductoStock = coproductostock};
		
		await IProductostock.DeleteByIdAsync(m);
		return TypedResults.NoContent();
	}

	static async Task<Results<Ok<IEnumerable<ProductoStockModel>>, ValidationProblem, NotFound>> SelAllAsync([AsParameters] ProductoStockFilter f, IProductoStockBusiness IProductostock, UserClaims user)
	{		
		IEnumerable<ProductoStockModel> r = await IProductostock.SelAllAsync(new());
		return TypedResults.Ok(r);
	}

	static async Task<Results<Ok<IEnumerable<ProductoStockModel>>, ValidationProblem, NotFound>> SelAllActiveAsync([AsParameters] ProductoStockFilter f, IProductoStockBusiness IProductostock, UserClaims user)
	{		
		IEnumerable<ProductoStockModel> r = await IProductostock.SelAllActiveAsync(new());
		return TypedResults.Ok(r);
	}

	static async Task<Results<Ok<ProductoStockModel>, NotFound, ValidationProblem>> SelByIdAsync(int coproductostock, IProductoStockBusiness IProductostock, UserClaims user)
	{
		ProductoStockModel m = new() { CoProductoStock = coproductostock};
		
		ProductoStockModel? i = await IProductostock.SelByIdAsync(m);
		if (i == null)
			return TypedResults.NotFound();
		return TypedResults.Ok(i);
	}

}
