// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: EndPoints class for the table "tblproductoindex"
// </auto-generated>
// -----------------------------------------------------------------------------

using Microsoft.AspNetCore.Http.HttpResults;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Mozo.Api.Catalogo;
/// <summary>
/// Clase estatica que para llamar al grupo de end points "tblproductoindex".
/// </summary>
public static partial class ProductoindexEndPoints
{
/// <summary>
/// Función que devuelve el grupo de end points de la entidad "tblproductoindex".
/// </summary>
	public static RouteGroupBuilder MapProductoindex(this RouteGroupBuilder g)
	{
		g.DisableAntiforgery().RequireAuthorization();
		g.MapPost("/", InsertAsync);
		g.MapPut("/", UpdateAsync);
		g.MapPatch("/state", UpdateStateAsync);
		g.MapDelete("/{coproductoindex:int}", DeleteByIdAsync);
		g.MapGet("/", SelAllAsync);
		g.MapGet("/active", SelAllActiveAsync);
		g.MapGet("/{coproductoindex:int}", SelByIdAsync);
		return g;
	}
}
/// <summary>
/// Clase estatica donde se encuentran los procedimientos y funciones de los end points "tblproductoindex".
/// </summary>
public static partial class ProductoindexEndPoints
{

	static async Task<Results<Created<int?>, ValidationProblem>> InsertAsync(ProductoindexModel m, IProductoindexBusiness IProductoindex, UserClaims user)
	{
		m = m.SetClaims(user);
		m.CoProductoindex = await IProductoindex.InsertAsync(m);
		return TypedResults.Created($"/{m.CoProductoindex}", m.CoProductoindex);
	}

	static async Task<Results<Ok<int?>, ValidationProblem>> UpdateAsync(ProductoindexModel m, IProductoindexBusiness IProductoindex, UserClaims user)
	{
		m = m.SetClaims(user);
		await IProductoindex.UpdateAsync(m);
		return TypedResults.Ok(m.CoProductoindex);
	}

	static async Task<Results<Ok<int?>, ValidationProblem>> UpdateStateAsync(ProductoindexModel m, IProductoindexBusiness IProductoindex, UserClaims user)
	{
		m = m.SetClaims(user);
		await IProductoindex.UpdateStateAsync(m);
		return TypedResults.Ok(m.CoProductoindex);
	}

	static async Task<Results<NoContent, ValidationProblem>> DeleteByIdAsync(int coproductoindex, IProductoindexBusiness IProductoindex, UserClaims user)
	{
		ProductoindexModel m = new() {CoProductoindex = coproductoindex};
		m = m.SetClaims(user);
		await IProductoindex.DeleteByIdAsync(m);
		return TypedResults.NoContent();
	}

	static async Task<Results<Ok<IEnumerable<ProductoindexModel>>, ValidationProblem, NotFound>> SelAllAsync([AsParameters] DynamicFilter<ProductoindexFilter> f, IProductoindexBusiness IProductoindex, UserClaims user)
	{
		ProductoindexModel m = f.ToModel<ProductoindexModel>(user);
		IEnumerable<ProductoindexModel> r = await IProductoindex.SelAllAsync(m);
		return TypedResults.Ok(r);
	}

	static async Task<Results<Ok<IEnumerable<ProductoindexModel>>, ValidationProblem, NotFound>> SelAllActiveAsync([AsParameters] DynamicFilter<ProductoindexFilter> f, IProductoindexBusiness IProductoindex, UserClaims user)
	{
		ProductoindexModel m = f.ToModel<ProductoindexModel>(user);
		IEnumerable<ProductoindexModel> r = await IProductoindex.SelAllActiveAsync(m);
		return TypedResults.Ok(r);
	}

	static async Task<Results<Ok<ProductoindexModel>, NotFound, ValidationProblem>> SelByIdAsync(int coproductoindex, IProductoindexBusiness IProductoindex, UserClaims user)
	{
		ProductoindexModel m = new() {CoProductoindex = coproductoindex};
		m = m.SetClaims(user);
		ProductoindexModel? i = await IProductoindex.SelByIdAsync(m);
		if (i == null)
			return TypedResults.NotFound();
		return TypedResults.Ok(i);
	}

}
