// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: EndPoints class for the table "tblproductoimpuesto"
// </auto-generated>
// -----------------------------------------------------------------------------

using Microsoft.AspNetCore.Http.HttpResults;

using Mozo.ApiSeguridad.Helper;
using Mozo.CatalogoBusiness;
using Mozo.Model.Catalogo;

using System.Collections.Generic;
using System.Threading.Tasks;

namespace Mozo.Api.Catalogo;
/// <summary>
/// Clase estatica que para llamar al grupo de end points "tblproductoimpuesto".
/// </summary>
public static partial class ProductoImpuestoEndPoints
{
/// <summary>
/// Función que devuelve el grupo de end points de la entidad "tblproductoimpuesto".
/// </summary>
	public static RouteGroupBuilder MapProductoImpuesto(this RouteGroupBuilder g)
	{
		g.DisableAntiforgery().RequireAuthorization();
		g.MapPost("/", InsertAsync);
		g.MapPut("/", UpdateAsync);
		g.MapPatch("/state", UpdateStateAsync);
		g.MapDelete("/{coproductoimpuesto:int}", DeleteByIdAsync);
		g.MapGet("/", SelAllAsync);
		g.MapGet("/active", SelAllActiveAsync);
		g.MapGet("/{coproductoimpuesto:int}", SelByIdAsync);
		return g;
	}
}
/// <summary>
/// Clase estatica donde se encuentran los procedimientos y funciones de los end points "tblproductoimpuesto".
/// </summary>
public static partial class ProductoImpuestoEndPoints
{

	static async Task<Results<Created<int?>, ValidationProblem>> InsertAsync(ProductoImpuestoModel m, IProductoImpuestoBusiness IProductoimpuesto, UserClaims user)
	{		
		m.CoProductoImpuesto = await IProductoimpuesto.InsertAsync(m);
		return TypedResults.Created($"/{m.CoProductoImpuesto}", m.CoProductoImpuesto);
	}

	static async Task<Results<Ok<int?>, ValidationProblem>> UpdateAsync(ProductoImpuestoModel m, IProductoImpuestoBusiness IProductoimpuesto, UserClaims user)
	{
		
		await IProductoimpuesto.UpdateAsync(m);
		return TypedResults.Ok(m.CoProductoImpuesto);
	}

	static async Task<Results<Ok<int?>, ValidationProblem>> UpdateStateAsync(ProductoImpuestoModel m, IProductoImpuestoBusiness IProductoimpuesto, UserClaims user)
	{
		
		await IProductoimpuesto.UpdateStateAsync(m);
		return TypedResults.Ok(m.CoProductoImpuesto);
	}

	static async Task<Results<NoContent, ValidationProblem>> DeleteByIdAsync(int coproductoimpuesto, IProductoImpuestoBusiness IProductoimpuesto, UserClaims user)
	{
		ProductoImpuestoModel m = new() { CoProductoImpuesto = coproductoimpuesto};
		
		await IProductoimpuesto.DeleteByIdAsync(m);
		return TypedResults.NoContent();
	}

	static async Task<Results<Ok<IEnumerable<ProductoImpuestoModel>>, ValidationProblem, NotFound>> SelAllAsync([AsParameters] ProductoImpuestoFilter f, IProductoImpuestoBusiness IProductoimpuesto, UserClaims user)
	{
		
		IEnumerable<ProductoImpuestoModel> r = await IProductoimpuesto.SelAllAsync(new());
		return TypedResults.Ok(r);
	}

	static async Task<Results<Ok<IEnumerable<ProductoImpuestoModel>>, ValidationProblem, NotFound>> SelAllActiveAsync([AsParameters] ProductoImpuestoFilter f, IProductoImpuestoBusiness IProductoimpuesto, UserClaims user)
	{		
		IEnumerable<ProductoImpuestoModel> r = await IProductoimpuesto.SelAllActiveAsync(new());
		return TypedResults.Ok(r);
	}

	static async Task<Results<Ok<ProductoImpuestoModel>, NotFound, ValidationProblem>> SelByIdAsync(int coproductoimpuesto, IProductoImpuestoBusiness IProductoimpuesto, UserClaims user)
	{
		ProductoImpuestoModel m = new() {CoProductoImpuesto = coproductoimpuesto};
		
		ProductoImpuestoModel? i = await IProductoimpuesto.SelByIdAsync(m);
		if (i == null)
			return TypedResults.NotFound();
		return TypedResults.Ok(i);
	}

}
