// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: EndPoints class for the table "tblproducto"
// </auto-generated>
// -----------------------------------------------------------------------------

using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;

using Mozo.ApiSeguridad.Helper;
using Mozo.CatalogoBusiness;
using Mozo.Model;
using Mozo.Model.Catalogo;

using System.Collections.Generic;
using System.Threading.Tasks;

using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Mozo.Api.Catalogo;
/// <summary>
/// Clase estatica que para llamar al grupo de end points "tblproducto".
/// </summary>
public static partial class ProductoEndPoints
{
/// <summary>
/// Función que devuelve el grupo de end points de la entidad "tblproducto".
/// </summary>
	public static RouteGroupBuilder MapProducto(this RouteGroupBuilder g)
	{
		g.DisableAntiforgery().RequireAuthorization();
		g.MapPost("/", InsertAsync);
		g.MapPut("/", UpdateAsync);
		g.MapPatch("/state", UpdateStateAsync);
		g.MapDelete("/{coproducto:int}", DeleteByIdAsync);
		g.MapGet("/", SelAllAsync).AllowAnonymous();
		g.MapGet("/active", SelAllActiveAsync);
		g.MapGet("/{coproducto:int}", SelByIdAsync).AllowAnonymous(); 
		return g;
	}
}
/// <summary>
/// Clase estatica donde se encuentran los procedimientos y funciones de los end points "tblproducto".
/// </summary>
public static partial class ProductoEndPoints
{

	static async Task<Results<Created<int?>, ValidationProblem>> InsertAsync([FromBody] ProductoModel m, IProductoBusiness IProducto)
	{		
		m.CoProducto = await IProducto.InsertAsync(m);
		return TypedResults.Created($"/{m.CoProducto}", m.CoProducto);
	}

	static async Task<Results<Ok<int?>, ValidationProblem>> UpdateAsync([FromBody] ProductoModel m, IProductoBusiness IProducto)
	{
	
		await IProducto.UpdateAsync(m);
		return TypedResults.Ok(m.CoProducto);
	}

	static async Task<Results<Ok<int?>, ValidationProblem>> UpdateStateAsync([FromBody] ProductoModel m, IProductoBusiness IProducto)
	{
		
		await IProducto.UpdateStateAsync(m);
		return TypedResults.Ok(m.CoProducto);
	}

	static async Task<Results<NoContent, ValidationProblem>> DeleteByIdAsync(int coproducto, IProductoBusiness IProducto)
	{
		ProductoModel m = new() {CoProducto = coproducto};	
		await IProducto.DeleteByIdAsync(m);
		return TypedResults.NoContent();
	}

	static async Task<Results<Ok<PaginationModel<ProductoModel>>, ValidationProblem, NotFound>> SelAllAsync([AsParameters] ProductoFilterDto f, IProductoBusiness IProducto)
	{     
		int rowCount = await IProducto.SelAllCountAsync(f);
        IEnumerable<ProductoModel> r = await IProducto.SelAllAsync(f);
        PaginationModel<ProductoModel> p = new(r, rowCount, f.PageSize, f.PageIndex);
        return TypedResults.Ok(p);
	}

	static async Task<Results<Ok<PaginationModel<ProductoModel>>, ValidationProblem, NotFound>> SelAllActiveAsync([AsParameters] ProductoFilterDto f, IProductoBusiness IProducto)
	{        
        int rowCount = await IProducto.SelAllActiveCountAsync(f);
        IEnumerable<ProductoModel> r = await IProducto.SelAllActiveAsync(f);
        PaginationModel<ProductoModel> p = new(r, rowCount, f.PageSize, f.PageIndex);
        return TypedResults.Ok(p);
	}

	static async Task<Results<Ok<ProductoModel>, NotFound, ValidationProblem>> SelByIdAsync(int coproducto, IProductoBusiness IProducto)
	{
		ProductoModel m = new() {CoProducto = coproducto};
		ProductoModel? i = await IProducto.SelByIdAsync(m);
		if (i == null)
			return TypedResults.NotFound();
		return TypedResults.Ok(i);
	}

}
