// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: EndPoints class for the table "tblproductoatributo"
// </auto-generated>
// -----------------------------------------------------------------------------

using Microsoft.AspNetCore.Http.HttpResults;

using Mozo.ApiSeguridad.Helper;
using Mozo.CatalogoBusiness;
using Mozo.Model.Catalogo;

using System.Collections.Generic;
using System.Threading.Tasks;

namespace Mozo.Api.Catalogo;
/// <summary>
/// Clase estatica que para llamar al grupo de end points "tblproductoatributo".
/// </summary>
public static partial class ProductoAtributoEndPoints
{
/// <summary>
/// Función que devuelve el grupo de end points de la entidad "tblproductoatributo".
/// </summary>
	public static RouteGroupBuilder MapProductoAtributo(this RouteGroupBuilder g)
	{
		g.DisableAntiforgery().RequireAuthorization();
		g.MapPost("/", InsertAsync);
		g.MapPut("/", UpdateAsync);
		g.MapPatch("/state", UpdateStateAsync);
		g.MapDelete("/{coproductoatributo:int}", DeleteByIdAsync);
		g.MapGet("/", SelAllAsync);
		g.MapGet("/active", SelAllActiveAsync);
		g.MapGet("/{coproductoatributo:int}", SelByIdAsync);
		return g;
	}
}
/// <summary>
/// Clase estatica donde se encuentran los procedimientos y funciones de los end points "tblproductoatributo".
/// </summary>
public static partial class ProductoAtributoEndPoints
{

	static async Task<Results<Created<int?>, ValidationProblem>> InsertAsync(ProductoAtributoModel m, IProductoAtributoBusiness IProductoatributo, UserClaims user)
	{		
		m.CoProductoAtributo = await IProductoatributo.InsertAsync(m);
		return TypedResults.Created($"/{m.CoProductoAtributo}", m.CoProductoAtributo);
	}

	static async Task<Results<Ok<int?>, ValidationProblem>> UpdateAsync(ProductoAtributoModel m, IProductoAtributoBusiness IProductoatributo, UserClaims user)
	{
		
		await IProductoatributo.UpdateAsync(m);
		return TypedResults.Ok(m.CoProductoAtributo);
	}

	static async Task<Results<Ok<int?>, ValidationProblem>> UpdateStateAsync(ProductoAtributoModel m, IProductoAtributoBusiness IProductoatributo, UserClaims user)
	{
		
		await IProductoatributo.UpdateStateAsync(m);
		return TypedResults.Ok(m.CoProductoAtributo);
	}

	static async Task<Results<NoContent, ValidationProblem>> DeleteByIdAsync(int coproductoatributo, IProductoAtributoBusiness IProductoatributo, UserClaims user)
	{
		ProductoAtributoModel m = new() { CoProductoAtributo = coproductoatributo};
		
		await IProductoatributo.DeleteByIdAsync(m);
		return TypedResults.NoContent();
	}

	static async Task<Results<Ok<IEnumerable<ProductoAtributoModel>>, ValidationProblem, NotFound>> SelAllAsync([AsParameters] ProductoAtributoFilter f, IProductoAtributoBusiness IProductoatributo, UserClaims user)
	{
	
		IEnumerable<ProductoAtributoModel> r = await IProductoatributo.SelAllAsync(new());
		return TypedResults.Ok(r);
	}

	static async Task<Results<Ok<IEnumerable<ProductoAtributoModel>>, ValidationProblem, NotFound>> SelAllActiveAsync([AsParameters] ProductoAtributoFilter f, IProductoAtributoBusiness IProductoatributo, UserClaims user)
	{
		
		IEnumerable<ProductoAtributoModel> r = await IProductoatributo.SelAllActiveAsync(new());
		return TypedResults.Ok(r);
	}

	static async Task<Results<Ok<ProductoAtributoModel>, NotFound, ValidationProblem>> SelByIdAsync(int coproductoatributo, IProductoAtributoBusiness IProductoatributo, UserClaims user)
	{
		ProductoAtributoModel m = new() { CoProductoAtributo = coproductoatributo};
		
		ProductoAtributoModel? i = await IProductoatributo.SelByIdAsync(m);
		if (i == null)
			return TypedResults.NotFound();
		return TypedResults.Ok(i);
	}

}
