// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-09-30
//     Description: Model class for the table "trfdocumentoidentidad"
// </auto-generated>
// -----------------------------------------------------------------------------

using System;
namespace Mozo.Model.Maestro;

public record DocumentoIdentidadFilter : BaseFilterDto   { }
/// <summary>
/// Entidad que representa la tabla "trfdocumentoidentidad".
/// </summary>
public class DocumentoIdentidadModel
{
  public int CoDocumentoIdentidad { get; set; }
  public int CoPais { get; set; }
  public string NoCodigo { get; set; }
  public string NoDocumentoIdentidad { get; set; }
  public string NoDocumentoIdentidadSigla { get; set; }
}
