// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-09-30
//     Description: Model class for the table "trfmoneda"
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace Mozo.Model.Maestro;

public record MonedaFilter : BaseFilterDto   { }
/// <summary>
/// Entidad que representa la tabla "trfmoneda".
/// </summary>
public class MonedaModel
{
  public int CoMoneda { get; set; }
  public string NoCodigoIso { get; set; }
  public int NuCodigoIso { get; set; }
  public string NoMoneda { get; set; }
  public string NoSimbolo { get; set; }
}
