// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-09-30
//     Description: Model class for the table "trfpais"
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace Mozo.Model.Maestro;

public record PaisFilter : BaseFilterDto   { }

/// <summary>
/// Entidad que representa la tabla "trfpais".
/// </summary>
public partial class PaisModel
{
  public string NoPais { get; set; }
  public string NoCodigoIso2 { get; set; }
  public string NoCodigoIso3 { get; set; }
  public string NoPrefijoTelefono { get; set; }
  public int CoPais { get; set; }
  public int? CoMoneda { get; set; }
}

public partial class PaisModel
{
    public MonedaModel Moneda { get; set; }    
}
