// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-09-30
//     Description: Model class for the table "trfunidadmedida"
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace Mozo.Model.Maestro;

public record UnidadMedidaFilter : BaseFilterDto 
{ }
/// <summary>
/// Entidad que representa la tabla "trfunidadmedida".
/// </summary>
public class UnidadMedidaModel
{
  public int CoUnidadMedida { get; set; }
  public int CoPais { get; set; }
  public string NoCodigoIso { get; set; }
  public string NoUnidadMedida { get; set; }
  public string NoSimbolo { get; set; }
}
