// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-03
//     Description: DataAcces class for the table "tblatributo"
// </auto-generated>
// -----------------------------------------------------------------------------

using Dapper;
using Npgsql;
using System.Threading.Tasks;
using Mozo.Helper.Enu;
using System.Data;
using Mozo.Model.Catalogo;
using Mozo.Helper.Global;
namespace Mozo.CatalogoData;

public interface IAtributoData
{
    Task<int> InsertAsync(AtributoModel c);
    Task UpdateAsync(AtributoModel c);
    Task UpdateStateAsync(AtributoModel c);
    Task DeleteByIdAsync(AtributoModel c);
    Task<AtributoModel?> SelByIdAsync(AtributoModel c);
    Task<IEnumerable<AtributoModel>> SelAllAsync(AtributoModel c);
    Task<IEnumerable<AtributoModel>> SelAllActiveAsync(AtributoModel c);
}
/// <summary>
/// Clase de acceso a datos que representa la tabla "tblatributo".
/// </summary>
public class AtributoData : IAtributoData
{
    private readonly string _schema = EnuCommon.BdDefault.Schema.Catalogo;
    private readonly IDbConnection _connection;

    private readonly UserContext _user;
    public AtributoData(IDbConnection connection, UserContext user)
    {
        _connection = connection;
        _user = user;
    }
    public async Task<int> InsertAsync(AtributoModel c)
    {
        (DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "NoAtributo",
            "CoTipodato",
            "CoCategoria",
            "NuOrden",
            "FlObligatorio",
            "FlFiltrable",
            "FlDescriptivo",
            "FlEstreg",
            "CoUsuCre"
        );
        string sql = @$"SELECT {_schema}.fn_atributo_insert({args})";
        return await _connection.ExecuteScalarAsync<int>(sql, pr);
    }

    public async Task UpdateAsync(AtributoModel c)
    {
        (DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "CoAtributo",
            "NoAtributo",
            "CoTipodato",
            "CoCategoria",
            "NuOrden",
            "FlObligatorio",
            "FlFiltrable",
            "FlDescriptivo",
            "FlEstreg",
            "CoUsuMod"
        );
        string sql = @$"CALL {_schema}.usp_atributo_update({args})";
        await _connection.ExecuteAsync(sql, pr);
    }

    public async Task UpdateStateAsync(AtributoModel c)
    {
        (DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "CoAtributo",
            "FlEstReg",
            "CoUsuMod"
        );
        string sql = @$"CALL {_schema}.usp_atributo_update_state({args})";
        await _connection.ExecuteAsync(sql, pr);
    }

    public async Task DeleteByIdAsync(AtributoModel c)
    {
        (DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "CoAtributo",
            "CoUsuEli"
        );
        string sql = @$"CALL {_schema}.usp_atributo_delete_by_id({args})";
        await _connection.ExecuteAsync(sql, pr);
    }

    public async Task<IEnumerable<AtributoModel>> SelAllAsync(AtributoModel c)
    {
        (DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa"
        );
        string sql = @$"SELECT * FROM {_schema}.fn_atributo_sel_all({args})";
        return await _connection.QueryAsync<AtributoModel>(sql, pr);
    }

    public async Task<IEnumerable<AtributoModel>> SelAllActiveAsync(AtributoModel c)
    {
        (DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa"
        );
        string sql = @$"SELECT * FROM {_schema}.fn_atributo_sel_all_active({args})";
        return await _connection.QueryAsync<AtributoModel>(sql, pr);
    }

    public async Task<AtributoModel?> SelByIdAsync(AtributoModel c)
    {
        (DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "CoAtributo"
        );
        string sql = @$"SELECT * FROM {_schema}.fn_atributo_sel_by_id({args})";
        return await _connection.QueryFirstOrDefaultAsync<AtributoModel>(sql, pr);
    }

}
