// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: DataAcces class for the table "tblproductoatributo"
// </auto-generated>
// -----------------------------------------------------------------------------

using Dapper;
using Npgsql;
using System.Threading.Tasks;
using Mozo.Helper.Enu;
using System.Data;
using Mozo.Model.Catalogo;
using Mozo.Helper.Global;
namespace Mozo.CatalogoData;
public interface IProductoAtributoData
{
	Task<int> InsertAsync(ProductoAtributoModel c);
	Task UpdateAsync(ProductoAtributoModel c);
	Task UpdateStateAsync(ProductoAtributoModel c);
	Task DeleteByIdAsync(ProductoAtributoModel c);
	Task<ProductoAtributoModel?> SelByIdAsync(ProductoAtributoModel c);
	Task<IEnumerable<ProductoAtributoModel>> SelAllAsync(ProductoAtributoModel c);
	Task<IEnumerable<ProductoAtributoModel>> SelAllActiveAsync(ProductoAtributoModel c);
}
/// <summary>
/// Clase de acceso a datos que representa la tabla "tblproductoatributo".
/// </summary>
public class ProductoAtributoData: IProductoAtributoData
{
	private readonly string _schema = EnuCommon.BdDefault.Schema.Catalogo;
	private readonly IDbConnection _connection;

    private readonly UserContext _user;
    public ProductoAtributoData(IDbConnection connection, UserContext user)
    {
        _connection = connection;
        _user = user;
    }

    public async Task<int> InsertAsync(ProductoAtributoModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoProductoAtributo",
			"CoProducto",
			"CoAtributo",
			"NoValor",
			"CoEmpresa",
			"FlEstreg",
			"CoUsuCre"
		);
		string sql = @$"SELECT {_schema}.fn_productoatributo_insert({args})";
		return await _connection.ExecuteScalarAsync<int>(sql, pr);
	}

	public async Task UpdateAsync(ProductoAtributoModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoProductoAtributo",
			"CoProducto",
			"CoAtributo",
			"NoValor",
			"CoEmpresa",
			"FlEstreg",
			"CoUsuMod"
		);
		string sql = @$"CALL {_schema}.usp_productoatributo_update({args})";
		await _connection.ExecuteAsync(sql, pr);
	}

	public async Task UpdateStateAsync(ProductoAtributoModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoProductoAtributo",
			"CoEmpresa",
			"FlEstReg",
			"CoUsuMod"
		);
		string sql = @$"CALL {_schema}.usp_productoatributo_update_state({args})";
		 await _connection.ExecuteAsync(sql, pr);
	}

	public async Task DeleteByIdAsync(ProductoAtributoModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoProductoAtributo",
			"CoEmpresa",
			"CoUsuEli"
		);
		string sql = @$"CALL {_schema}.usp_productoatributo_delete_by_id({args})";
		await _connection.ExecuteAsync(sql, pr);
	}

	public async Task<IEnumerable<ProductoAtributoModel>> SelAllAsync(ProductoAtributoModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa"
		);
		string sql = @$"SELECT * FROM {_schema}.fn_productoatributo_sel_all({args})";
		return await _connection.QueryAsync<ProductoAtributoModel>(sql, pr);
	}

	public async Task<IEnumerable<ProductoAtributoModel>> SelAllActiveAsync(ProductoAtributoModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa"
		);
		string sql = @$"SELECT * FROM {_schema}.fn_productoatributo_sel_all_active({args})";
		return await _connection.QueryAsync<ProductoAtributoModel>(sql, pr);
	}

	public async Task<ProductoAtributoModel?> SelByIdAsync(ProductoAtributoModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoProductoAtributo",
			"CoEmpresa"
		);
		string sql = @$"SELECT * FROM {_schema}.fn_productoatributo_sel_by_id({args})";
		return await _connection.QueryFirstOrDefaultAsync<ProductoAtributoModel>(sql, pr);
	}

}
