// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: DataAcces class for the table "tblproductoimpuesto"
// </auto-generated>
// -----------------------------------------------------------------------------

using Dapper;
using Npgsql;
using System.Threading.Tasks;
using Mozo.Helper.Enu;
using System.Data;
using Mozo.Model.Catalogo;
using Mozo.Helper.Global;
namespace Mozo.CatalogoData;
public interface IProductoImpuestoData
{
	Task<int> InsertAsync(ProductoImpuestoModel c);
	Task UpdateAsync(ProductoImpuestoModel c);
	Task UpdateStateAsync(ProductoImpuestoModel c);
	Task DeleteByIdAsync(ProductoImpuestoModel c);
	Task<ProductoImpuestoModel?> SelByIdAsync(ProductoImpuestoModel c);
	Task<IEnumerable<ProductoImpuestoModel>> SelAllAsync(ProductoImpuestoModel c);
	Task<IEnumerable<ProductoImpuestoModel>> SelAllActiveAsync(ProductoImpuestoModel c);
}
/// <summary>
/// Clase de acceso a datos que representa la tabla "tblproductoimpuesto".
/// </summary>
public class ProductoImpuestoData : IProductoImpuestoData
{
	private readonly string _schema = EnuCommon.BdDefault.Schema.Catalogo;
	private readonly IDbConnection _connection;

    private readonly UserContext _user;
    public ProductoImpuestoData(IDbConnection connection, UserContext user)
    {
        _connection = connection;
        _user = user;
    }

    public async Task<int> InsertAsync(ProductoImpuestoModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",		
			"CoProducto",
			"CoImpuesto",
			"CoImpuestoHijo",			
			"PqTaza",
			"CoUsuCre"
		);
		string sql = @$"SELECT {_schema}.fn_productoimpuesto_insert({args})";
		return await _connection.ExecuteScalarAsync<int>(sql, pr);
	}

	public async Task UpdateAsync(ProductoImpuestoModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
			"CoProductoImpuesto",
			"CoProducto",
			"CoImpuesto",
			"CoImpuestohijo",			
			"PqTaza",
			"CoUsuMod"
		);
		string sql = @$"CALL {_schema}.usp_productoimpuesto_update({args})";
		await _connection.ExecuteAsync(sql, pr);
	}

	public async Task UpdateStateAsync(ProductoImpuestoModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
			"CoProductoImpuesto",
			"FlEstReg",
			"CoUsuMod"
		);
		string sql = @$"CALL {_schema}.usp_productoimpuesto_update_state({args})";
		 await _connection.ExecuteAsync(sql, pr);
	}

	public async Task DeleteByIdAsync(ProductoImpuestoModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "CoProductoImpuesto",
			"CoUsuEli"
		);
		string sql = @$"CALL {_schema}.usp_productoimpuesto_delete_by_id({args})";
		await _connection.ExecuteAsync(sql, pr);
	}

	public async Task<IEnumerable<ProductoImpuestoModel>> SelAllAsync(ProductoImpuestoModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa"
		);
		string sql = @$"SELECT * FROM {_schema}.fn_productoimpuesto_sel_all({args})";
		return await _connection.QueryAsync<ProductoImpuestoModel>(sql, pr);
	}

	public async Task<IEnumerable<ProductoImpuestoModel>> SelAllActiveAsync(ProductoImpuestoModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa"
		);
		string sql = @$"SELECT * FROM {_schema}.fn_productoimpuesto_sel_all_active({args})";
		return await _connection.QueryAsync<ProductoImpuestoModel>(sql, pr);
	}

	public async Task<ProductoImpuestoModel?> SelByIdAsync(ProductoImpuestoModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "CoProductoImpuesto"
        );
		string sql = @$"SELECT * FROM {_schema}.fn_productoimpuesto_sel_by_id({args})";
		return await _connection.QueryFirstOrDefaultAsync<ProductoImpuestoModel>(sql, pr);
	}

}
