// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: DataAcces class for the table "tblproductoindex"
// </auto-generated>
// -----------------------------------------------------------------------------

using Dapper;
using Npgsql;
using System.Threading.Tasks;
using Mozo.Helper.Enu;
using System.Data;
namespace Mozo.CatalogoData;
public interface IProductoindexData
{
	Task<int> InsertAsync(ProductoindexModel c);
	Task UpdateAsync(ProductoindexModel c);
	Task UpdateStateAsync(ProductoindexModel c);
	Task DeleteByIdAsync(ProductoindexModel c);
	Task<ProductoindexModel?> SelByIdAsync(ProductoindexModel c);
	Task<IEnumerable<ProductoindexModel>> SelAllAsync(ProductoindexModel c);
	Task<IEnumerable<ProductoindexModel>> SelAllActiveAsync(ProductoindexModel c);
}
/// <summary>
/// Clase de acceso a datos que representa la tabla "tblproductoindex".
/// </summary>
public class ProductoindexData: IProductoindexData
{
	private readonly string _schema = EnuCommon.BdDefault.Schema.Maestro;
	private readonly IDbConnection _connection;

	public ProductoindexData(IDbConnection connection)
	{
		_connection = connection;
	}

	public async Task<int> InsertAsync(ProductoindexModel c)
	{
		(DynamicParameters pr, string args) = Glo.Build(c,
			"CoProductoindex",
			"CoEmpresa",
			"CoProducto",
			"NoProducto",
			"TxDescripcioncorta",
			"JsOnatributo",
			"TxBusqueda",
			"CoCategoria",
			"CoUsuCre"
		);
		string sql = @$"SELECT {_schema}.fn_productoindex_insert({args})";
		return await _connection.ExecuteScalarAsync<int>(sql, pr);
	}

	public async Task UpdateAsync(ProductoindexModel c)
	{
		(DynamicParameters pr, string args) = Glo.Build(c,
			"CoProductoindex",
			"CoEmpresa",
			"CoProducto",
			"NoProducto",
			"TxDescripcioncorta",
			"JsOnatributo",
			"TxBusqueda",
			"CoCategoria",
			"CoUsuMod"
		);
		string sql = @$"CALL {_schema}.usp_productoindex_update({args})";
		await _connection.ExecuteAsync(sql, pr);
	}

	public async Task UpdateStateAsync(ProductoindexModel c)
	{
		(DynamicParameters pr, string args) = Glo.Build(c,
			"CoProductoindex",
			"CoEmpresa",
			"FlEstReg",
			"CoUsuMod"
		);
		string sql = @$"CALL {_schema}.usp_productoindex_update_state({args})";
		 await _connection.ExecuteAsync(sql, pr);
	}

	public async Task DeleteByIdAsync(ProductoindexModel c)
	{
		(DynamicParameters pr, string args) = Glo.Build(c,
			"CoProductoindex",
			"CoEmpresa",
			"CoUsuEli"
		);
		string sql = @$"CALL {_schema}.usp_productoindex_delete_by_id({args})";
		await _connection.ExecuteAsync(sql, pr);
	}

	public async Task<IEnumerable<ProductoindexModel>> SelAllAsync(ProductoindexModel c)
	{
		(DynamicParameters pr, string args) = Glo.Build(c,
			"CoEmpresa"
		);
		string sql = @$"SELECT * FROM {_schema}.fn_productoindex_sel_all({args})";
		return await _connection.QueryAsync<ProductoindexModel>(sql, pr);
	}

	public async Task<IEnumerable<ProductoindexModel>> SelAllActiveAsync(ProductoindexModel c)
	{
		(DynamicParameters pr, string args) = Glo.Build(c,
			"CoEmpresa"
		);
		string sql = @$"SELECT * FROM {_schema}.fn_productoindex_sel_all_active({args})";
		return await _connection.QueryAsync<ProductoindexModel>(sql, pr);
	}

	public async Task<ProductoindexModel?> SelByIdAsync(ProductoindexModel c)
	{
		(DynamicParameters pr, string args) = Glo.Build(c,
			"CoProductoindex",
			"CoEmpresa"
		);
		string sql = @$"SELECT * FROM {_schema}.fn_productoindex_sel_by_id({args})";
		return await _connection.QueryFirstOrDefaultAsync<ProductoindexModel>(sql, pr);
	}

}
