// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: DataAcces class for the table "tblproductostock"
// </auto-generated>
// -----------------------------------------------------------------------------

using Dapper;
using Npgsql;
using System.Threading.Tasks;
using Mozo.Helper.Enu;
using Mozo.Helper.Global;
using System.Data;
using Mozo.Model.Catalogo;
namespace Mozo.CatalogoData;
public interface IProductoStockData
{
	Task<int> InsertAsync(ProductoStockModel c);
	Task UpdateAsync(ProductoStockModel c);
	Task UpdateStateAsync(ProductoStockModel c);
	Task DeleteByIdAsync(ProductoStockModel c);
	Task<ProductoStockModel?> SelByIdAsync(ProductoStockModel c);
	Task<IEnumerable<ProductoStockModel>> SelAllAsync(ProductoStockModel c);
	Task<IEnumerable<ProductoStockModel>> SelAllActiveAsync(ProductoStockModel c);
}
/// <summary>
/// Clase de acceso a datos que representa la tabla "tblproductostock".
/// </summary>
public class ProductoStockData : IProductoStockData
{
	private readonly string _schema = EnuCommon.BdDefault.Schema.Catalogo;
	private readonly IDbConnection _connection;

    private readonly UserContext _user;
    public ProductoStockData(IDbConnection connection, UserContext user)
    {
        _connection = connection;
        _user = user;
    }
    public async Task<int> InsertAsync(ProductoStockModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",		
			"CoProducto",
			"CoLocal",
			"CoAlmacen",
			"QtInicial",
			"QtMaxima",
			"QtMinima",			
			"FlDefault",
			"CoUsuCre"
		);
		string sql = @$"SELECT {_schema}.fn_productostock_insert({args})";
		return await _connection.ExecuteScalarAsync<int>(sql, pr);
	}

	public async Task UpdateAsync(ProductoStockModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
			"CoProductoStock",
			"CoProducto",
			"CoLocal",
			"CoAlmacen",
			"QtInicial",
			"QtMaxima",
			"QtMinima",			
			"FlDefault",
			"CoUsuMod"
		);
		string sql = @$"CALL {_schema}.usp_productostock_update({args})";
		await _connection.ExecuteAsync(sql, pr);
	}

	public async Task UpdateStateAsync(ProductoStockModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "CoProductoStock",
			"FlEstReg",
			"CoUsuMod"
		);
		string sql = @$"CALL {_schema}.usp_productostock_update_state({args})";
		 await _connection.ExecuteAsync(sql, pr);
	}

	public async Task DeleteByIdAsync(ProductoStockModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "CoProductoStock",
			"CoUsuEli"
		);
		string sql = @$"CALL {_schema}.usp_productostock_delete_by_id({args})";
		await _connection.ExecuteAsync(sql, pr);
	}

	public async Task<IEnumerable<ProductoStockModel>> SelAllAsync(ProductoStockModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa"
		);
		string sql = @$"SELECT * FROM {_schema}.fn_productostock_sel_all({args})";
		return await _connection.QueryAsync<ProductoStockModel>(sql, pr);
	}

	public async Task<IEnumerable<ProductoStockModel>> SelAllActiveAsync(ProductoStockModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa"
		);
		string sql = @$"SELECT * FROM {_schema}.fn_productostock_sel_all_active({args})";
		return await _connection.QueryAsync<ProductoStockModel>(sql, pr);
	}

	public async Task<ProductoStockModel?> SelByIdAsync(ProductoStockModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "CoProductoStock"
        );
		string sql = @$"SELECT * FROM {_schema}.fn_productostock_sel_by_id({args})";
		return await _connection.QueryFirstOrDefaultAsync<ProductoStockModel>(sql, pr);
	}

}
