// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: DataAcces class for the table "tblproducto"
// </auto-generated>
// -----------------------------------------------------------------------------

using Dapper;

using Mozo.Helper.Enu;
using Mozo.Helper.Global;
using Mozo.Model.Catalogo;
using Mozo.Model.Seguridad.Auth;

using Npgsql;

using System.Data;
using System.Text.Json;
using System.Threading.Tasks;
namespace Mozo.CatalogoData;

public interface IProductoData
{
    Task<int> InsertAsync(ProductoModel c);
    Task UpdateAsync(ProductoModel c);
    Task UpdateStateAsync(ProductoModel c);
    Task DeleteByIdAsync(ProductoModel c);
    Task<ProductoModel?> SelByIdAsync(ProductoModel c);
    Task<IEnumerable<ProductoModel>> SelAllAsync(ProductoFilterDto c);
    Task<int> SelAllCountAsync(ProductoFilterDto c);
    Task<IEnumerable<ProductoModel>> SelAllActiveAsync(ProductoFilterDto c);
    Task<int> SelAllActiveCountAsync(ProductoFilterDto c);
}
/// <summary>
/// Clase de acceso a datos que representa la tabla "tblproducto".
/// </summary>
public class ProductoData : IProductoData
{
    private readonly string _schema = EnuCommon.BdDefault.Schema.Catalogo;
    private readonly IDbConnection _connection;
    private readonly UserContext _user;
    public ProductoData(IDbConnection connection, UserContext user)
    {
        _connection = connection;
        _user = user;
    }

    public async Task<int> InsertAsync(ProductoModel c)
    {
        (DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "NoCodigointerno",
            "CoMarca",
            "CoLaboratorio",
            "NoProducto",
            "NoModelo",
            "CoUnidadmedidainventario",
            "CoUnidadmedidacompra",
            "CoUnidadmedidaventa",
            "SsFactorcompra",
            "CoProveedorprincipal",
            "TxDescripcioncorta",
            "CoCategoria",
            "CoCategoriahijo",
            "CoTipo",
            "FlImpuesto",
            "FlInventario",
            "NoCodigofiscal",
            "SsFactorventa",
            "FlImpuestoexento",
            "CoUsuCre"
        );

        string sql = @$"SELECT {_schema}.fn_producto_insert({args})";
        return await _connection.ExecuteScalarAsync<int>(sql, pr);
    }

    public async Task UpdateAsync(ProductoModel c)
    {
        (DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "CoProducto",
            "NoCodigointerno",
            "CoMarca",
            "CoLaboratorio",
            "NoProducto",
            "NoModelo",
            "CoUnidadmedidainventario",
            "CoUnidadmedidacompra",
            "CoUnidadmedidaventa",
            "SsFactorcompra",
            "CoProveedorprincipal",
            "TxDescripcioncorta",
            "CoCategoria",
            "CoCategoriahijo",
            "CoTipo",
            "FlImpuesto",
            "FlInventario",
            "NoCodigofiscal",
            "SsFactorventa",
            "FlImpuestoexento",
            "CoUsuMod"
        );

        string sql = @$"CALL {_schema}.usp_producto_update({args})";
        await _connection.ExecuteAsync(sql, pr);
    }

    public async Task UpdateStateAsync(ProductoModel c)
    {
        (DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "CoProducto",
            "FlEstReg",
            "CoUsuMod"
        );
        string sql = @$"CALL {_schema}.usp_producto_update_state({args})";
        await _connection.ExecuteAsync(sql, pr);
    }

    public async Task DeleteByIdAsync(ProductoModel c)
    {
        (DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "CoProducto",
            "CoUsuEli"
        );
        string sql = @$"CALL {_schema}.usp_producto_delete_by_id({args})";
        await _connection.ExecuteAsync(sql, pr);
    }

    public async Task<IEnumerable<ProductoModel>> SelAllAsync(ProductoFilterDto c)
    {
        (DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "CoProveedorPrincipal",
            "CoMarca",
            "NoInputSearch",
            "PageSize",
            "PageIndex"
        );        

        string sql = @$"SELECT * FROM {_schema}.fn_producto_sel_all({args})";      
        return await _connection.QueryAsync<ProductoModel>(sql, pr);
    }

    public async Task<int> SelAllCountAsync(ProductoFilterDto c)
    {
        (DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "CoProveedorPrincipal",
            "CoMarca",
            "NoInputSearch"          
        );

        string sql = @$"SELECT * FROM {_schema}.fn_producto_sel_all_count({args})";
        return await _connection.ExecuteScalarAsync<int>(sql, pr);
    }


    public async Task<IEnumerable<ProductoModel>> SelAllActiveAsync(ProductoFilterDto c)
    {
        (DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "PageSize",
            "CursorId",
            "Direction"
         );

        string sql = @$"SELECT * FROM {_schema}.fn_producto_sel_all_active({args})";
        return await _connection.QueryAsync<ProductoModel>(sql, pr);
    }
    public async Task<int> SelAllActiveCountAsync(ProductoFilterDto c)
    {
        (DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona, "CoEmpresa");

        string sql = @$"SELECT * FROM {_schema}.fn_producto_sel_all_count({args})";
        return await _connection.ExecuteScalarAsync<int>(sql, pr);
    }
    public async Task<ProductoModel?> SelByIdAsync(ProductoModel c)
    {
        (DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "CoProducto"
        );
        string sql = @$"SELECT * FROM {_schema}.fn_producto_sel_by_id({args})";
        return await _connection.QueryFirstOrDefaultAsync<ProductoModel>(sql, pr);
    }

}
