// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: DataAcces class for the table "tblproductoprecio"
// </auto-generated>
// -----------------------------------------------------------------------------

using Dapper;
using Npgsql;
using System.Threading.Tasks;
using Mozo.Helper.Enu;
using System.Data;
using Mozo.Model.Catalogo;
using Mozo.Helper.Global;
namespace Mozo.CatalogoData;

public interface IProductoPrecioData
{
	Task<int> InsertAsync(ProductoPrecioModel c);
	Task UpdateAsync(ProductoPrecioModel c);
	Task UpdateStateAsync(ProductoPrecioModel c);
	Task DeleteByIdAsync(ProductoPrecioModel c);
	Task<ProductoPrecioModel?> SelByIdAsync(ProductoPrecioModel c);
	Task<IEnumerable<ProductoPrecioModel>> SelAllAsync(ProductoPrecioModel c);
	Task<IEnumerable<ProductoPrecioModel>> SelAllActiveAsync(ProductoPrecioModel c);
}
/// <summary>
/// Clase de acceso a datos que representa la tabla "tblproductoprecio".
/// </summary>
public class ProductoPrecioData : IProductoPrecioData
{
	private readonly string _schema = EnuCommon.BdDefault.Schema.Catalogo;
	private readonly IDbConnection _connection;

    private readonly UserContext _user;
    public ProductoPrecioData(IDbConnection connection, UserContext user)
    {
        _connection = connection;
        _user = user;
    }

    public async Task<int> InsertAsync(ProductoPrecioModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",			
			"CoTipoprecio",
			"CoProducto",
			"SsPrecio",			
			"CoMoneda",
			"CoUsuCre"
		);
		string sql = @$"SELECT {_schema}.fn_productoprecio_insert({args})";
		return await _connection.ExecuteScalarAsync<int>(sql, pr);
	}

	public async Task UpdateAsync(ProductoPrecioModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
			"CoProductoPrecio",
			"CoTipoprecio",
			"CoProducto",
			"SsPrecio",			
			"CoMoneda",
			"CoUsuMod"
		);
		string sql = @$"CALL {_schema}.usp_productoprecio_update({args})";
		await _connection.ExecuteAsync(sql, pr);
	}

	public async Task UpdateStateAsync(ProductoPrecioModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "CoProductoPrecio",
			"FlEstReg",
			"CoUsuMod"
		);
		string sql = @$"CALL {_schema}.usp_productoprecio_update_state({args})";
		 await _connection.ExecuteAsync(sql, pr);
	}

	public async Task DeleteByIdAsync(ProductoPrecioModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "CoProductoPrecio",
			"CoUsuEli"
		);
		string sql = @$"CALL {_schema}.usp_productoprecio_delete_by_id({args})";
		await _connection.ExecuteAsync(sql, pr);
	}

	public async Task<IEnumerable<ProductoPrecioModel>> SelAllAsync(ProductoPrecioModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa"
		);
		string sql = @$"SELECT * FROM {_schema}.fn_productoprecio_sel_all({args})";
		return await _connection.QueryAsync<ProductoPrecioModel>(sql, pr);
	}

	public async Task<IEnumerable<ProductoPrecioModel>> SelAllActiveAsync(ProductoPrecioModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa"
		);
		string sql = @$"SELECT * FROM {_schema}.fn_productoprecio_sel_all_active({args})";
		return await _connection.QueryAsync<ProductoPrecioModel>(sql, pr);
	}

	public async Task<ProductoPrecioModel?> SelByIdAsync(ProductoPrecioModel c)
	{
		(DynamicParameters pr, string args) = BuildDinamicParameter.Build(c, _user.CoEmpresa, _user.CoPersona,
            "CoEmpresa",
            "CoProductoPrecio"
        );
		string sql = @$"SELECT * FROM {_schema}.fn_productoprecio_sel_by_id({args})";
		return await _connection.QueryFirstOrDefaultAsync<ProductoPrecioModel>(sql, pr);
	}

}
