// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-01
//     Description: Business class for the table "tblatributo"
// </auto-generated>
// -----------------------------------------------------------------------------

using Mozo.CatalogoData;
using Mozo.Model.Catalogo;

using System.Collections.Generic;
using System.Threading.Tasks;

namespace Mozo.CatalogoBusiness;
public interface IAtributoBusiness
{
    Task<int> InsertAsync(AtributoModel c);
    Task UpdateAsync(AtributoModel c);
    Task UpdateStateAsync(AtributoModel c);
    Task DeleteByIdAsync(AtributoModel c);
    Task<AtributoModel?> SelByIdAsync(AtributoModel c);
    Task<IEnumerable<AtributoModel>> SelAllAsync(AtributoModel c);
    Task<IEnumerable<AtributoModel>> SelAllActiveAsync(AtributoModel c);
}
/// <summary>
/// Clase de negocios que representa la tabla "tblatributo".
/// </summary>
public class AtributoBusiness : IAtributoBusiness
{
    private readonly IAtributoData _data;

    public AtributoBusiness(IAtributoData data)
    {
        _data = data;
    }

    public async Task<int> InsertAsync(AtributoModel c) => await _data.InsertAsync(c);
    public async Task UpdateAsync(AtributoModel c) => await _data.UpdateAsync(c);
    public async Task UpdateStateAsync(AtributoModel c) => await _data.UpdateAsync(c);
    public async Task DeleteByIdAsync(AtributoModel c) => await _data.DeleteByIdAsync(c);
    public async Task<IEnumerable<AtributoModel>> SelAllAsync(AtributoModel c) => await _data.SelAllAsync(c);
    public async Task<IEnumerable<AtributoModel>> SelAllActiveAsync(AtributoModel c) => await _data.SelAllActiveAsync(c);
    public async Task<AtributoModel?> SelByIdAsync(AtributoModel c) => await _data.SelByIdAsync(c);
}
