// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: Business class for the table "tblproductoimpuesto"
// </auto-generated>
// -----------------------------------------------------------------------------
using Mozo.CatalogoData;
using System.Collections.Generic;
using System.Threading.Tasks;
using Mozo.Model.Catalogo;

namespace Mozo.CatalogoBusiness;
public interface IProductoImpuestoBusiness
{
     Task<int> InsertAsync(ProductoImpuestoModel c);
     Task UpdateAsync(ProductoImpuestoModel c);
     Task UpdateStateAsync(ProductoImpuestoModel c);
     Task DeleteByIdAsync(ProductoImpuestoModel c);
     Task<ProductoImpuestoModel?> SelByIdAsync(ProductoImpuestoModel c);
     Task<IEnumerable<ProductoImpuestoModel>> SelAllAsync(ProductoImpuestoModel c);
     Task<IEnumerable<ProductoImpuestoModel>> SelAllActiveAsync(ProductoImpuestoModel c);
}
/// <summary>
/// Clase de negocios que representa la tabla "tblproductoimpuesto".
/// </summary>
public class ProductoImpuestoBusiness : IProductoImpuestoBusiness
{
    private readonly IProductoImpuestoData _data;

    public ProductoImpuestoBusiness(IProductoImpuestoData data)
     {
     _data = data;
    }

    public async Task<int> InsertAsync(ProductoImpuestoModel c) => await _data.InsertAsync(c);
    public async Task UpdateAsync(ProductoImpuestoModel c) => await _data.UpdateAsync(c);
    public async Task UpdateStateAsync(ProductoImpuestoModel c) => await _data.UpdateAsync(c);
    public async Task DeleteByIdAsync(ProductoImpuestoModel c) => await _data.DeleteByIdAsync(c);
    public async Task<IEnumerable<ProductoImpuestoModel>> SelAllAsync(ProductoImpuestoModel c) => await _data.SelAllAsync(c);
    public async Task<IEnumerable<ProductoImpuestoModel>> SelAllActiveAsync(ProductoImpuestoModel c) => await _data.SelAllActiveAsync(c);
    public async Task<ProductoImpuestoModel?> SelByIdAsync(ProductoImpuestoModel c) => await _data.SelByIdAsync(c);
}
