// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: Business class for the table "tblproducto"
// </auto-generated>
// -----------------------------------------------------------------------------

using Mozo.CatalogoData;
using Mozo.Helper.Global;
using Mozo.Model.Catalogo;
using Mozo.Model.Seguridad.Auth;

using System.Collections.Generic;
using System.Threading.Tasks;

namespace Mozo.CatalogoBusiness;

public interface IProductoBusiness
{
    Task<int> InsertAsync(ProductoModel c);
    Task UpdateAsync(ProductoModel c);
    Task UpdateStateAsync(ProductoModel c);
    Task DeleteByIdAsync(ProductoModel c);
    Task<ProductoModel?> SelByIdAsync(ProductoModel c);
    Task<IEnumerable<ProductoModel>> SelAllAsync(ProductoFilterDto c);
    Task<int> SelAllCountAsync(ProductoFilterDto c);
    Task<IEnumerable<ProductoModel>> SelAllActiveAsync(ProductoFilterDto c);
    Task<int> SelAllActiveCountAsync(ProductoFilterDto c);
}
/// <summary>
/// Clase de negocios que representa la tabla "tblproducto".
/// </summary>
public class ProductoBusiness : IProductoBusiness
{
    private readonly IProductoData _data;
    public ProductoBusiness(IProductoData data)
    {
        _data = data;
    }

    public async Task<int> InsertAsync(ProductoModel c) => await _data.InsertAsync(c);
    public async Task UpdateAsync(ProductoModel c) => await _data.UpdateAsync(c);
    public async Task UpdateStateAsync(ProductoModel c) => await _data.UpdateAsync(c);
    public async Task DeleteByIdAsync(ProductoModel c) => await _data.DeleteByIdAsync(c);
    public async Task<ProductoModel?> SelByIdAsync(ProductoModel c) => await _data.SelByIdAsync(c);
    public async Task<IEnumerable<ProductoModel>> SelAllAsync(ProductoFilterDto c) => await _data.SelAllAsync(c);
     public async Task<int> SelAllCountAsync(ProductoFilterDto c) => await _data.SelAllCountAsync(c);
    public async Task<IEnumerable<ProductoModel>> SelAllActiveAsync(ProductoFilterDto c) => await _data.SelAllActiveAsync(c);
    public async Task<int> SelAllActiveCountAsync(ProductoFilterDto c) => await _data.SelAllActiveCountAsync(c);


}
