// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: Business class for the table "tblproductoatributo"
// </auto-generated>
// -----------------------------------------------------------------------------

using Mozo.CatalogoData;
using Mozo.Model.Catalogo;

using System.Collections.Generic;
using System.Threading.Tasks;

namespace Mozo.CatalogoBusiness;
public interface IProductoAtributoBusiness
{
     Task<int> InsertAsync(ProductoAtributoModel c);
     Task UpdateAsync(ProductoAtributoModel c);
     Task UpdateStateAsync(ProductoAtributoModel c);
     Task DeleteByIdAsync(ProductoAtributoModel c);
     Task<ProductoAtributoModel?> SelByIdAsync(ProductoAtributoModel c);
     Task<IEnumerable<ProductoAtributoModel>> SelAllAsync(ProductoAtributoModel c);
     Task<IEnumerable<ProductoAtributoModel>> SelAllActiveAsync(ProductoAtributoModel c);
}
/// <summary>
/// Clase de negocios que representa la tabla "tblproductoatributo".
/// </summary>
public class ProductoAtributoBusiness : IProductoAtributoBusiness
{
    private readonly IProductoAtributoData _data;

    public ProductoAtributoBusiness(IProductoAtributoData data)
     {
     _data = data;
    }

    public async Task<int> InsertAsync(ProductoAtributoModel c) => await _data.InsertAsync(c);
    public async Task UpdateAsync(ProductoAtributoModel c) => await _data.UpdateAsync(c);
    public async Task UpdateStateAsync(ProductoAtributoModel c) => await _data.UpdateAsync(c);
    public async Task DeleteByIdAsync(ProductoAtributoModel c) => await _data.DeleteByIdAsync(c);
    public async Task<IEnumerable<ProductoAtributoModel>> SelAllAsync(ProductoAtributoModel c) => await _data.SelAllAsync(c);
    public async Task<IEnumerable<ProductoAtributoModel>> SelAllActiveAsync(ProductoAtributoModel c) => await _data.SelAllActiveAsync(c);
    public async Task<ProductoAtributoModel?> SelByIdAsync(ProductoAtributoModel c) => await _data.SelByIdAsync(c);
}
