// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: Business class for the table "tblproductoprecio"
// </auto-generated>
// -----------------------------------------------------------------------------

using Mozo.CatalogoData;
using Mozo.Model.Catalogo;

using System.Collections.Generic;
using System.Threading.Tasks;

namespace Mozo.CatalogoBusiness;
public interface IProductoPrecioBusiness
{
     Task<int> InsertAsync(ProductoPrecioModel c);
     Task UpdateAsync(ProductoPrecioModel c);
     Task UpdateStateAsync(ProductoPrecioModel c);
     Task DeleteByIdAsync(ProductoPrecioModel c);
     Task<ProductoPrecioModel?> SelByIdAsync(ProductoPrecioModel c);
     Task<IEnumerable<ProductoPrecioModel>> SelAllAsync(ProductoPrecioModel c);
     Task<IEnumerable<ProductoPrecioModel>> SelAllActiveAsync(ProductoPrecioModel c);
}
/// <summary>
/// Clase de negocios que representa la tabla "tblproductoprecio".
/// </summary>
public class ProductoPrecioBusiness : IProductoPrecioBusiness
{
    private readonly IProductoPrecioData _data;

    public ProductoPrecioBusiness(IProductoPrecioData data)
     {
     _data = data;
    }

    public async Task<int> InsertAsync(ProductoPrecioModel c) => await _data.InsertAsync(c);
    public async Task UpdateAsync(ProductoPrecioModel c) => await _data.UpdateAsync(c);
    public async Task UpdateStateAsync(ProductoPrecioModel c) => await _data.UpdateAsync(c);
    public async Task DeleteByIdAsync(ProductoPrecioModel c) => await _data.DeleteByIdAsync(c);
    public async Task<IEnumerable<ProductoPrecioModel>> SelAllAsync(ProductoPrecioModel c) => await _data.SelAllAsync(c);
    public async Task<IEnumerable<ProductoPrecioModel>> SelAllActiveAsync(ProductoPrecioModel c) => await _data.SelAllActiveAsync(c);
    public async Task<ProductoPrecioModel?> SelByIdAsync(ProductoPrecioModel c) => await _data.SelByIdAsync(c);
}
