// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: Business class for the table "tblproductostock"
// </auto-generated>
// -----------------------------------------------------------------------------

using Mozo.CatalogoData;
using Mozo.Model.Catalogo;

using System.Collections.Generic;
using System.Threading.Tasks;

namespace Mozo.CatalogoBusiness;
public interface IProductoStockBusiness
{
     Task<int> InsertAsync(ProductoStockModel c);
     Task UpdateAsync(ProductoStockModel c);
     Task UpdateStateAsync(ProductoStockModel c);
     Task DeleteByIdAsync(ProductoStockModel c);
     Task<ProductoStockModel?> SelByIdAsync(ProductoStockModel c);
     Task<IEnumerable<ProductoStockModel>> SelAllAsync(ProductoStockModel c);
     Task<IEnumerable<ProductoStockModel>> SelAllActiveAsync(ProductoStockModel c);
}
/// <summary>
/// Clase de negocios que representa la tabla "tblproductostock".
/// </summary>
public class ProductoStockBusiness: IProductoStockBusiness
{
    private readonly IProductoStockData _data;

    public ProductoStockBusiness(IProductoStockData data)
     {
     _data = data;
    }

    public async Task<int> InsertAsync(ProductoStockModel c) => await _data.InsertAsync(c);
    public async Task UpdateAsync(ProductoStockModel c) => await _data.UpdateAsync(c);
    public async Task UpdateStateAsync(ProductoStockModel c) => await _data.UpdateAsync(c);
    public async Task DeleteByIdAsync(ProductoStockModel c) => await _data.DeleteByIdAsync(c);
    public async Task<IEnumerable<ProductoStockModel>> SelAllAsync(ProductoStockModel c) => await _data.SelAllAsync(c);
    public async Task<IEnumerable<ProductoStockModel>> SelAllActiveAsync(ProductoStockModel c) => await _data.SelAllActiveAsync(c);
    public async Task<ProductoStockModel?> SelByIdAsync(ProductoStockModel c) => await _data.SelByIdAsync(c);
}
