// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-06
//     Description: Business class for the table "tblproductoindex"
// </auto-generated>
// -----------------------------------------------------------------------------

using System.Collections.Generic;
using System.Threading.Tasks;

namespace Mozo.CatalogoBusiness;
public interface IProductoindexBusiness
{
     Task<int> InsertAsync(ProductoindexModel c);
     Task UpdateAsync(ProductoindexModel c);
     Task UpdateStateAsync(ProductoindexModel c);
     Task DeleteByIdAsync(ProductoindexModel c);
     Task<ProductoindexModel?> SelByIdAsync(ProductoindexModel c);
     Task<IEnumerable<ProductoindexModel>> SelAllAsync(ProductoindexModel c);
     Task<IEnumerable<ProductoindexModel>> SelAllActiveAsync(ProductoindexModel c);
}
/// <summary>
/// Clase de negocios que representa la tabla "tblproductoindex".
/// </summary>
public class ProductoindexBusiness: IProductoindexBusiness
    {
    private readonly IProductoindexData _data;

    public ProductoindexBusiness(IProductoindexData data)
     {
     _data = data;
    }

    public async Task<int> InsertAsync(ProductoindexModel c) => await _data.InsertAsync(c);
    public async Task UpdateAsync(ProductoindexModel c) => await _data.UpdateAsync(c);
    public async Task UpdateStateAsync(ProductoindexModel c) => await _data.UpdateAsync(c);
    public async Task DeleteByIdAsync(ProductoindexModel c) => await _data.DeleteByIdAsync(c);
    public async Task<IEnumerable<ProductoindexModel>> SelAllAsync(ProductoindexModel c) => await _data.SelAllAsync(c);
    public async Task<IEnumerable<ProductoindexModel>> SelAllActiveAsync(ProductoindexModel c) => await _data.SelAllActiveAsync(c);
    public async Task<ProductoindexModel?> SelByIdAsync(ProductoindexModel c) => await _data.SelByIdAsync(c);
}
