// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-01
//     Description: Model class for the table "trfclasificacionfiscal"
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace Mozo.Model.Contabilidad.Contabilidad;

public record ClasificacionFiscalFilter : BaseFilterDto //ClasificacionFiscalFilter>
{

}

/// <summary>
/// Entidad que representa la tabla "trfclasificacionfiscal".
/// </summary>
public class ClasificacionFiscalModel
{
  public int CoClasificacionfiscal { get; set; }
  public int CoPais { get; set; }
  public string NoCodigo { get; set; }
  public string NoClasificacionfiscal { get; set; }
}
