// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-01
//     Description: Model class for the table "trfcomprobantepago"
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace Mozo.Model.Contabilidad.Contabilidad;

public record ComprobantePagoFilter : BaseFilterDto //ComprobantePagoFilter>
{

}

/// <summary>
/// Entidad que representa la tabla "trfcomprobantepago".
/// </summary>
public class ComprobantePagoModel
{
  public int CoComprobantePago { get; set; }
  public int CoPais { get; set; }
  public string NoCodigo { get; set; }
  public string NoComprobantePago { get; set; }
  public string NoComprobantePagoSigla { get; set; }
}
