// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-01
//     Description: Model class for the table "trfimpuestohijo"
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace Mozo.Model.Contabilidad.Contabilidad;

public record ImpuestoHijoFilter : BaseFilterDto //ImpuestoHijoFilter>
{

}

/// <summary>
/// Entidad que representa la tabla "trfimpuestohijo".
/// </summary>
public class ImpuestoHijoModel
{
  public int CoImpuestoHijo { get; set; }
  public int CoImpuesto { get; set; }
  public string NoCodigo { get; set; }
  public string NoImpuestoHijo { get; set; }
  public string NoMetodo { get; set; }
  public decimal? PqTasa { get; set; }
  public decimal? SsMonto { get; set; }
  public int? CoUnidadMedida { get; set; }
  public int CoPais { get; set; }
}
