// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-01
//     Description: Model class for the table "trfimpuesto"
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace Mozo.Model.Contabilidad.Contabilidad;

public record ImpuestoFilter : BaseFilterDto //ImpuestoFilter>
{

}

/// <summary>
/// Entidad que representa la tabla "trfimpuesto".
/// </summary>
public class ImpuestoModel
{
  public int CoImpuesto { get; set; }
  public string NoCodigo { get; set; }
  public string NoImpuesto { get; set; }
  public string NoTipo { get; set; }
  public decimal? PqTasa { get; set; }
  public int CoPais { get; set; }
}
