// -----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CodeGenerator
//     Author: Jonatán Abregú
//     Creation Date: 2025-10-01
//     Description: Model class for the table "trfmediopago"
// </auto-generated>
// -----------------------------------------------------------------------------

using System;

namespace Mozo.Model.Contabilidad.Contabilidad;

public record MedioPagoFilter : BaseFilterDto //MedioPagoFilter>
{

}


/// <summary>
/// Entidad que representa la tabla "trfmediopago".
/// </summary>
public class MedioPagoModel
{
  public int CoMedioPago { get; set; }
  public int CoPais { get; set; }
  public string NoCodigo { get; set; }
  public string NoMedioPago { get; set; }
}
